# Generated by Django 2.1.5 on 2019-05-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='processing',
            field=models.BooleanField(default=True),
        ),
    ]
