# Generated by Django 2.1.5 on 2019-05-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='csv',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
