# Generated by Django 2.1.5 on 2019-05-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_campaign_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='email_variable',
            field=models.CharField(default='email', max_length=150),
        ),
    ]
