# Generated by Django 2.1.5 on 2019-05-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_mailsentlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailsentlog',
            name='user',
        ),
        migrations.AddField(
            model_name='mailsentlog',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='mailsentlog',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='mailsentlog',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
