# Generated by Django 2.1.5 on 2019-05-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_mail_read_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='mailtrack',
            field=models.BooleanField(default=True),
        ),
    ]
