# Generated by Django 2.0.5 on 2018-07-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkmail',
            name='subject',
            field=models.CharField(default='', max_length=150),
        ),
    ]
