# Generated by Django 2.0.5 on 2018-07-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_bulkmail_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkmail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
